apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-platform

spec:
  replicas: 3

  selector:
    matchLabels:
      app: gitops-platform

  template:
    metadata:
      labels:
        app: gitops-platform

    spec:
      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: gitops-platform
        image: ghcr.io/thahir-devops-lab/gitops-platform:2813a0e

        imagePullPolicy: Always

        ports:
        - containerPort: 5000
