apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: gitops-platform
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: gitops-platform

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s