name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: gitops-platform

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run Tests
        run: |
          pytest app/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            .

      - name: Run Trivy Scan
  uses: aquasecurity/trivy-action@v0.33.1
  with:
    image-ref: ghcr.io/${{ github.repository_owner }}/gitops-platform:${IMAGE_TAG}
    format: table
    exit-code: 1
    ignore-unfixed: true
    severity: CRITICAL,HIGH
      - name: Push Latest
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Version Tag
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
